packages:
  - ./cdk
  - ./app
  - ./app/cdk
  - ./cdk/function

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
