packages:
  - ./cdk
  - ./app
  - ./app/cdk
  - ./cdk/function

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  '@eslint/js': '>=10'
  '@stylistic/eslint-plugin': '>=5.0.0'
  eslint: '>=10'
  minimatch@<10.2.1: '>=10.2.1'
